export type RolePermission =
  | 'inventory-movements'
  | 'products-control'
  | 'categories-control'
  | 'csv-export'
  | 'locations-control'
  | 'notifications-control'
  | 'suppliers-control'
  | 'reports'
  | 'all'
