export { RegisterProductController } from './register-product-controller'
export { DeleteProductsController } from './delete-products-controller'
export { ListProductsController } from './list-products-controller'
export { UpdateProductController } from './update-product-controller'
export { GetProductsController } from './get-products-controller'
