export { RegisterProductController } from './register-product-controller'
export { DeleteProductsController } from './delete-products-controller'
export { ListProductsController } from './list-products-controller'
export { UpdateProductController } from './update-product-controller'
export { GetProductController } from './get-product-controller'
export { DeleteImageController } from './delete-image-controller'
