export { ProductsRoutes } from './products-routes'
export { InventoryMovementsRoutes } from './inventory-movements-routes'
export { FileStorageRoutes } from './file-storage-routes'
export { ReportsRoutes } from './reports-routes'
export { CategoriesRoutes } from './categories-routes'
