export type IconName =
  | 'dashboard'
  | 'inventory'
  | 'record'
  | 'edit'
  | 'arrow-up'
  | 'arrow-down'
  | 'arrow-up-down'
  | 'product'
  | 'category'
  | 'location'
  | 'employee'
  | 'supplier'
  | 'stock'
  | 'notification'
  | 'ellipses'
  | 'menu-hamburguer'
  | 'close'
